# secret.yaml — go-you-secrets. Contains live values (POC only; move to a secret store later).
# Apply with: kubectl apply -n go-you-poc -f deploy/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: go-you-secrets
  namespace: go-you-poc
type: Opaque
stringData:
  MYSQL_DSN: "dbadmin:aLG#tR4EU_nu@tcp(main.cluster-clmcecso4av4.ap-south-1.rds.amazonaws.com:3306)/user?parseTime=true&timeout=5s"
  PROXY_URL: "http://brd-customer-hl_34977069-zone-residential-country-in-dns-local:8cv6uyaqczwg@servercountry-in.brd.superproxy.io:22225"
